auth:
    path: /auth
    defaults: { _controller: 'CMS\Controllers\AuthenticationController::setupAuthentication'}

login:
  path: /login
  defaults: { _controller: 'CMS\Controllers\AuthenticationController::login'}

blog_list:
    path:     /
    defaults: { _controller: 'CMS\Controllers\DefaultController::helloAction' }

article:
    path:     /articles/{id}
    defaults: { _controller: 'CMS\Controllers\DefaultController::getArticleById' }

new_article:
    path:     /new_article
    defaults: { _controller: 'CMS\Controllers\DefaultController::newArticle' }

delete_article:
    path:     /delete_article/{id}
    defaults: { _controller: 'CMS\Controllers\DefaultController::deleteArticle' }
