blog_list:
    path:     /
    defaults: { _controller: 'CMS\Controllers\DefaultController::helloAction' }

article:
    path:     /articles/{id}
    defaults: { _controller: 'CMS\Controllers\DefaultController::getArticleById' }
